# Generated by Django 3.1.1 on 2020-09-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportDistance',
            fields=[
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('distance', models.IntegerField()),
                ('routeCode', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AirportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('IATA', models.CharField(max_length=3)),
                ('ICAO', models.CharField(max_length=4)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.IntegerField()),
                ('timezone', models.FloatField()),
                ('DST', models.CharField(max_length=3)),
                ('tzDatabaseTimeZone', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
            ],
        ),
    ]
